### ISSUE TITLE
New teams-insiders version.

### ISSUE THREAD

**Issue by mathieuf20** [ogarcia/pkgbuilds#1]
Hi.

There is a new teams-insiders version available. 

pkgver=1.3.00.14051

As I am not really aware of how pkgbuild files work in arch, I prefered to just open an issue. Hope it's ok.

Thanks!

**Comment by mathieuf20** [comment]
Just saw it got updated on the AUR. Sorry!

**Comment by ogarcia** [comment]
> Just saw it got updated on the AUR. Sorry!

No problem :-)

For mark a package as outdated you can use _Flag package out-of-date_ in AUR :wink:

**Comment by mathieuf20** [comment]
Didn't know that! thank you!
