### ISSUE TITLE
Autofirma: Parece funcionar con Java-runtime=18

### ISSUE THREAD

**Issue by Noxbru** [ogarcia/pkgbuilds#10]
Hoy me ha tocado utilizar el paquete de autofirma del AUR, pero como no tengo instalado java-runtime=11, sino la versión 18 (que es la que está en los repos de Arch) he 'engañado' al pkgbuild y al propio programa para que tirasen con java-runtime=18. Se queja al arrancar, pero funciona.

¿Se podría entonces añadir java-runtime=18 como 'soportado'?

**Comment by ogarcia** [comment]
El problema es que la versión de Java _oficialmente soportada_ por autofirma no va mas allá de la 11. Que a ti te funcione la 18 con tu administración pública no quiere decir que a todo el mundo de funcione, a lo mejor a otro usuario le peta al firmar en la web de su ayuntamiento.

Si ves que a ti te funciona bien con `java-runtime=18` mi consejo es que simplemente lo dejes así modificado y listo. El paquete no es algo que se actualice con frecuencia (la última actualización es de diciembre del año pasado) y si quitamos actualizaciones menores por ajustes en el paquete (que ya no se van a volver a realizar), la anterior es de mayo de 2019, por lo que no te va a requerir mantenimiento. Además, quien sabe, a lo mejor para la próxima versión que publiquen soportan oficialmente Java 18 (soñar es gratis).
