### ISSUE TITLE
[SUGERENCIA] ¿Paquete para flatpak? 

### ISSUE THREAD

**Issue by trinukso** [ogarcia/pkgbuilds#12]
Hola.

Felicidades por tu trabajo y tiempo. ¿Te has planteado empaquetar autofirma como flatpak en flathub? Es simplemente una sugerencia pues no te podría ayudar en como hacerlo. Pero, actualmente, estaría muy bien tener el autofirma en flathub.

Gracias.

**Comment by ogarcia** [comment]
Buenas @trinukso 

Lo de empaquetar en flatpak se sale un poquito bastante del alcance de este repositorio (ten en cuenta que esto va de empaquetar para Arch Linux en su propio sistema de paquetes).

Dicho esto, la verdad es que no tengo ningún tipo de experiencia con flatpak. No lo uso y nunca he tenido la necesidad de utilizarlo (al menos no en Arch Linux), por lo que poco voy a poder aportar ahí. En cualquier caso IMHO el empaquetar en flatpak es algo que debería ser siempre tarea del desarrollador del software (ya que es algo que no varía entre distribuciones) y no de terceros, aunque aquí me parece harto complicado que la gente que hace autofirma de el paso.

En fin, lo único que se me ocurre es que podrías proponerlo en el repositorio de autofirma a ver si al menos alguien envía una merge request con los ficheros de configuración y luego se podría crear el paquete con ellos, pero no te voy a dar ninguna esperanza porque de todas las mejoras y bugs que he abierto yo no se ha tocado ni la primera.

Saludos.

**Comment by trinukso** [comment]
Gracias por tu respuesta.

Yo también dudo muchísimo que esta gente empaquete para flathub. Pero bueno, se puede abrir la sugerencia en su sitio, como bien dices. A lo mejor sugiriendo que dejen de empaquetar en deb y/o rpm a favor de flatpak y publicando en flathub.

Saludos.

**Comment by ogarcia** [comment]
Si, si abres una issue en su repositorio ponla aquí y así le doy un :+1: :wink:

**Comment by trinukso** [comment]
jejeje ¡gracias! No prometo nada... no tengo muchas ganas. Parece que 
está más de moda usar ***@***.*** que este engendro javero o lo que 
demonios sea, jeje.
