### ISSUE TITLE
AutoFirma: Falla al realizar la firma online

### ISSUE THREAD

**Issue by rodajc** [ogarcia/pkgbuilds#13]
Me ha dejado de funcionar. Después de pasar por no sé cuantas pantallas de la Agencia Española de Protección de Datos falla autofirma con este error:

```
javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
(....)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
(....)
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

Firma archivos locales perfectamente. Es online que falla. Cómo soluciono esto?

Utilizo autofirma v1.8.2 y la última versión de archlinux y firefox.

**Comment by ogarcia** [comment]
Parece que da un error porque no hay ruta de certificado, como si no se confiase en algún certificado raíz. De todas formas prueba lo siguiente:

1. La mejor forma de probar autofirma es en esta web https://www.sededgsfp.gob.es/es/Paginas/TestAutofirma.aspx si ahí te funciona entonces el problema es de la web en la que estas intentando firmar que tiene algo mal hecho.
2. Si no te funciona la web anterior prueba a borrar el directorio `.afirma` de tu home. No te preocupes por el contenido, lo genera de nuevo a arrancar autofirma (si te sientes mas cómodo le puedes hacer una copia).
3. Prueba con Chromium (por descartar que no tengas nada raro en tu navegador).

**Comment by rodajc** [comment]
Muchas gracias Óscar. He hecho la prueba que recomiendas bajo 1. y el resultado es:
`Firma realizada correctamente`

Estuve buscando dónde hacer esta prueba cuando me fallaba pero no dí con esta página. Gracias por tu respuesta tan rápida.

Ya me parecía raro porque he firmado online varias veces. La verdad es que no suele ir bien a la primera, pero si insistes un poco acaba yendo.

Antes de cerrar este issue, me puedes recomendar cómo seguir con esto ya que la página de la AEPD debe de causar este problema?

**Comment by ogarcia** [comment]
> Antes de cerrar este issue, me puedes recomendar cómo seguir con esto ya que la página de la AEPD debe de causar este problema?

La verdad es que poco te puedo decir. Si autofirma te funciona en la web de prueba esta claro que el problema lo tienen en la web de AEPD que vete a saber que implementación han hecho (o si lo han llegado a probar).

Dos opciones que se me ocurren serían o bien intentar ponerte en contacto con alguien que lleve esa web (abajo del todo tienen un teléfono en el que seguramente te puedan decir algo) o bien probar con una máquina virtual Windows por si esta gente solo ha hecho los deberes para ese operativo. De las dos opciones la primera es la mas recomendable, pero posiblemente te termines dando contra el muro de la administración pública...

Poco mas se puede hacer porque ya ves que a nivel software esta todo funcionando.

**Comment by rodajc** [comment]
Vale.

Creo que ya me estoy "dando contra el muro de la administración pública", como tu dices, jeje.

 Gracias de todas maneras!

**Comment by rodajc** [comment]
En [Registro Electrónico Común (redsara.es)](https://rec.redsara.es/registro/action/are/acceso.do) tampoco funciona. Ya no es solo en la AEPD.

Funcionaría con una versión anterior?

**Comment by ogarcia** [comment]
Buenas, yo estoy probando con todos los validadores y en todos me funciona sin problema:
https://sede.carm.es/cryptoApplet/ayuda/probarautofirma.html
https://sede.dgt.gob.es/es/otros-tramites/verificacion-certificados/padi/padi.shtml
https://valide.redsara.es/valide/firmar/ejecutar.html

No puedo probar con lo que tu dices porque no tengo nada que presentar. En cuanto a probar una versión anterior, por intentarlo no pierdes nada, tienes el histórico en AUR: https://aur.archlinux.org/cgit/aur.git/log/?h=autofirma elige el commit de la versión que quieras y puedes descargar un tar.gz con el código.

**Comment by rodajc** [comment]
Acabo de finalizar el trámite en el Registro Electrónico Común RedSara con éxito:

> Se ha realizado correctamente su presentación.
> Descargue su justificante pulsando sobre la imagen
> 

He seguido exactamente el mismo procedimiento de ayer y con la misma v1.8.2. Decidí repetir para comprobar que no fuera un problema con el adblocker que utilizo, pero no lo vi bloquear ninguna página en el proceso. Yo no lo entiendo.

Ya no pruebo con ninguna versión anterior porque funciona con la v1.8.2.

**Comment by rodajc** [comment]
> cerré el navegador lo abrí de nuevo y como un tiro

Si. Me suena. Incluso sin cerrar el navegador. Siempre hay que probar otra vez. Lo que pasa es que, si tienes que pasar por no sé cuántas pantallas hasta que llegues por fin a la de la firma, y te falla ahí, no estás para empezar de nuevo :sweat:.

Una cosa que he aprendido es pasar de la página de la AEPD y usar la del Registro Electrónico Común RedSara. Va más al grano. No te pone una serie de opciones que no sabes cuál elegir. Lo único es encontrar al organismo en cuestión en la lista al principio.

Pues nada. Gracias por tu ayuda! :thumbsup:

**Comment by David-UPCT** [comment]
Perdonadme, no sé si es correcto escribir en un mensaje cerrado, si es así abriría uno nuevo. 

Tengo el mismo problema que el mensaje original en la web de letras del tesoro 

https://wwws.tesoro.es/

Se abre una ventana con código de error SAF16: error al recuperar los datos del servidor intermedio junto a una retahila de errores de JAVA idénticos a los que comentaba rodajc en el primer mensaje:

![Captura desde 2023-10-24 10-21-52](https://github.com/ogarcia/pkgbuilds/assets/5481139/c3ff01cc-a316-44b9-aaca-3751b3bb842d)

Este problema se produce desde verano, antes yo podía comprar o reinvertir sin que me diese error de autofirma. Desde entonces lo habré probado como 40 ó 50 veces: en 3 ordenadores diferentes con Archlinux completamente actualizado, con Chromium y con Firefox, con distintas versiones de openjdk, tanto con autofirma como con autofirma-bin y con autofirma-git que hay en AUR, e incluso bajando la versión de Autofirma a la 1.7.2 (me suelo guardar los .pkg de las cosas que instalo en AUR, he rescatado la versión anterior de ahí). No ha habido manera.

Todos los validadores online de Autofirma que habéis comentado (el de Seguros y Fondos de pensiones, el de la CARM, el de la DGT... incluso uno propio que hay en mi universidad) funcionan bien. El único fallo me aparece en la web del tesoro, y solamente desde hace unos meses, antes me iba bien. Les escribí detallando el problema pero ni me contestaron.

No sé si se os ocurre algo, la única solución que he encontrado es usar un ordenador con Windows o Ubuntu.

**Comment by ogarcia** [comment]
@David-UPCT por lo que comentas desde luego parece que es un problema que tienen ellos en su web ya que si funciona en cualquier sitio excepto en su paǵina claramente algo no están haciendo bien.

Lo que me parece raro es que en Ubuntu funcione ya que a fin de cuentas es casi lo mismo que usar Arch, pero bueno, si te funciona así yo lo que haría sería tener una máquina virtual preparada para este caso.

En cuanto a escribir a la admon. pública pidiendo soporte, no hay nada que rascar. En mi vida solo en contadas ocasiones me han contestado y cuando lo hacen es una respuesta genérica del tipo "en mi casa funciona" o "utiliza windows".

**Comment by David-UPCT** [comment]
> @David-UPCT por lo que comentas desde luego parece que es un problema que tienen ellos en su web ya que si funciona en cualquier sitio excepto en su paǵina claramente algo no están haciendo bien.
> 
> Lo que me parece raro es que en Ubuntu funcione ya que a fin de cuentas es casi lo mismo que usar Arch, pero bueno, si te funciona así yo lo que haría sería tener una máquina virtual preparada para este caso.
> 
> En cuanto a escribir a la admon. pública pidiendo soporte, no hay nada que rascar. En mi vida solo en contadas ocasiones me han contestado y cuando lo hacen es una respuesta genérica del tipo "en mi casa funciona" o "utiliza windows".

Pues tenías toda la razón, no es algo propio de Archlinux: he probado con una instalación limpia (vía máquina virtual) de Ubuntu y de Debian y el problema era exactamente el mismo. 

La parte buena es que he encontrado como resolverlo, gracias a la ayuda de los errores SAF11 y SAF16 de

https://cau.sci.uma.es/faq/index.php?action=artikel&cat=32&id=298&artlang=es

La solución en mi caso ha sido entrar en Autofirma y desmarcar Herramientas -> Preferencias -> Aceptar solo conexiones con sitios seguros. Para otra vez probaré a mantener esa pestaña activada e incluir el dominio del Tesoro como Dominio seguro, pero de momento el problema está resuelto.

Muchas gracias por todo.
