### ISSUE TITLE
GRAVE: No se ha podido obtener la ultima version disponible

### ISSUE THREAD

**Issue by Musikolo** [ogarcia/pkgbuilds#2]
Hola

He visto que el configurador FNMT no funciona. He probado con dos versiones de Java 8 & 11 y ambas producen el mismo error.

**Java 1.8:**
```
[musikolo@MyPc ~]$ java -version
openjdk version "1.8.0_265"
OpenJDK Runtime Environment Corretto-8.265.01.1 (build 1.8.0_265-b01)
OpenJDK 64-Bit Server VM Corretto-8.265.01.1 (build 25.265-b01, mixed mode)
[musikolo@MyPc ~]$ 
[musikolo@MyPc ~]$ 
[musikolo@MyPc ~]$ /usr/bin/configuradorfnmt
nov 16, 2020 2:57:12 PM es.gob.fnmt.cert.certrequest.CertRequest main
INFORMACIÓN: Modo de depuracion desactivado
nov 16, 2020 2:57:12 PM es.gob.fnmt.cert.certrequest.CertRequest main
INFORMACIÓN: Version actual de la aplicacion: '1'
nov 16, 2020 2:57:12 PM es.gob.fnmt.cert.certrequest.CertRequest printSystemInfo
INFORMACIÓN: Aplicacion FNMT de solicitud de certificados version 1.
 Sistema operativo: Linux.
 Version del sistema operativo: 5.9.4-arch1-1.
 Version de Java: 1.8.0_265.
 Arquitectura del JRE: 64 bits.
 Fabricante de la JVM: Amazon.com Inc..
 Idioma por defecto: es_ES.
 Tamano actual en memoria: 481MB.
 Tamano maximo de memoria: 7120MB.
 Memoria actualmente libre: 356MB.
nov 16, 2020 2:57:13 PM es.gob.fnmt.cert.certrequest.ProxyUtil setDefaultProxy
INFORMACIÓN: No se usara proxy para las conexiones HTTP
nov 16, 2020 2:57:13 PM es.gob.fnmt.cert.certrequest.ProxyUtil setDefaultProxy
INFORMACIÓN: No se usara proxy para las conexiones HTTPS
nov 16, 2020 2:57:13 PM es.gob.fnmt.cert.certrequest.Updater$1 checkServerTrusted
INFORMACIÓN: Verificado correctamente el certificado SSL: SEDE ELECTRONICA FNMT-RCM
nov 16, 2020 2:57:14 PM es.gob.afirma.core.misc.http.UrlHttpManagerImpl enableSslChecks
INFORMACIÓN: Habilitadas comprobaciones SSL
nov 16, 2020 2:57:14 PM es.gob.fnmt.cert.certrequest.Updater getLatestVersion
GRAVE: No se ha podido obtener la ultima version disponible desde https://www.sede.fnmt.gob.es/documents/10445900/10528994/certrequest.version.linux: es.gob.afirma.core.misc.http.HttpError
nov 16, 2020 2:57:14 PM es.gob.fnmt.cert.certrequest.Updater isNewVersionAvailable
GRAVE: No se puede comprobar si hay versiones nuevas del aplicativo
nov 16, 2020 2:57:14 PM es.gob.fnmt.cert.certrequest.Updater lambda$checkForUpdates$1
INFORMACIÓN: No se ha podido comprobar la disponibilidad de nueva version: java.lang.UnsupportedOperationException: No se puede comprobar si hay versiones nuevas del aplicativo, no hay informacion sobre la ultima version disponible
[musikolo@MyPc ~]$
```

**Java 11:**
```
[musikolo@MyPc ~]$ java -version
openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment (build 11.0.8+10)
OpenJDK 64-Bit Server VM (build 11.0.8+10, mixed mode)
[musikolo@MyPc ~]$ 
[musikolo@MyPc ~]$ 
[musikolo@MyPc ~]$ /usr/bin/configuradorfnmt
nov. 16, 2020 2:57:40 P. M. es.gob.fnmt.cert.certrequest.CertRequest main
INFORMACIÓN: Modo de depuracion desactivado
nov. 16, 2020 2:57:40 P. M. es.gob.fnmt.cert.certrequest.CertRequest main
INFORMACIÓN: Version actual de la aplicacion: '1'
nov. 16, 2020 2:57:40 P. M. es.gob.fnmt.cert.certrequest.CertRequest printSystemInfo
INFORMACIÓN: Aplicacion FNMT de solicitud de certificados version 1.
 Sistema operativo: Linux.
 Version del sistema operativo: 5.9.4-arch1-1.
 Version de Java: 11.0.8.
 Arquitectura del JRE: 64 bits.
 Fabricante de la JVM: Oracle Corporation.
 Idioma por defecto: es_ES.
 Tamano actual en memoria: 502MB.
 Tamano maximo de memoria: 8010MB.
 Memoria actualmente libre: 329MB.
nov. 16, 2020 2:57:40 P. M. es.gob.fnmt.cert.certrequest.ProxyUtil setDefaultProxy
INFORMACIÓN: No se usara proxy para las conexiones HTTP
nov. 16, 2020 2:57:40 P. M. es.gob.fnmt.cert.certrequest.ProxyUtil setDefaultProxy
INFORMACIÓN: No se usara proxy para las conexiones HTTPS
nov. 16, 2020 2:57:41 P. M. es.gob.fnmt.cert.certrequest.Updater$1 checkServerTrusted
INFORMACIÓN: Verificado correctamente el certificado SSL: SEDE ELECTRONICA FNMT-RCM
nov. 16, 2020 2:57:41 P. M. es.gob.afirma.core.misc.http.UrlHttpManagerImpl enableSslChecks
INFORMACIÓN: Habilitadas comprobaciones SSL
nov. 16, 2020 2:57:41 P. M. es.gob.fnmt.cert.certrequest.Updater getLatestVersion
GRAVE: No se ha podido obtener la ultima version disponible desde https://www.sede.fnmt.gob.es/documents/10445900/10528994/certrequest.version.linux: es.gob.afirma.core.misc.http.HttpError
nov. 16, 2020 2:57:41 P. M. es.gob.fnmt.cert.certrequest.Updater isNewVersionAvailable
GRAVE: No se puede comprobar si hay versiones nuevas del aplicativo
nov. 16, 2020 2:57:41 P. M. es.gob.fnmt.cert.certrequest.Updater lambda$checkForUpdates$1
INFORMACIÓN: No se ha podido comprobar la disponibilidad de nueva version: java.lang.UnsupportedOperationException: No se puede comprobar si hay versiones nuevas del aplicativo, no hay informacion sobre la ultima version disponible
[musikolo@MyPc ~]$
```

Gracias.

**Comment by ogarcia** [comment]
Buenas,

Ese error es normal, me lo da a mi también. Me temo que han metido la pata de alguna manera y la aplicación va a mirar a una URL que no existe a ver si hay una versión nueva.

¿Cómo usas la aplicación? Ten en cuenta que no esta pensada para ejecutarla directamente, sino que te vas a la web para pedir un nuevo certificado y es la propia web la que la abre el configurador (a través de xdg-open) y te pide que le metas una contraseña para la llave que genera. Si la lanzas directamente solo te va a aparecer un cuadro de dialogo para configurar el proxy y en cuanto le des a OK ya se cierra.

Personalmente no he hecho mas que el primer paso, lanzar la aplicación desde la web y solicitar la llave. No he realizado todavía el siguiente porque por ahora no me toca hacer un nuevo certificado. Yo entiendo que una vez que valides la identidad en la oficina y vuelvas a descargar el certificado, harás el mismo proceso desde la web y a partir de ahí la aplicación ya te mostrará algo mas que el dialogo, al menos eso es lo que me han comentado que pasa. La verdad es que todo el mundo se ha quejado de que no tenga una interfaz que simplemente te diga que no tienes solicitudes (o si tienes alguna en curso que te las muestre), pero bueno, con la admon. hemos topado :shrug: 

Ya me cuentas.

**Comment by Musikolo** [comment]
Hola:


He probado con Firefox y Vivaldi (Chrome) y en ambos me sale un error. 
**Firefox 82**:
![image](https://user-images.githubusercontent.com/13580107/99402273-c6d1f080-28ae-11eb-9087-10eb60590eb9.png)

**Vivaldi 3.4** (Chrome):
![image](https://user-images.githubusercontent.com/13580107/99402426-f4b73500-28ae-11eb-9c3a-5aa30e5f2883.png)

![image](https://user-images.githubusercontent.com/13580107/99402484-039de780-28af-11eb-971b-ab7428129fdb.png)

Yo uso KDE Plasma. ¿Me podrías adjuntar una captura de la pantalla en la que se puede lanzar la aplicación desde el navegador? 

Por otro lado, ¿necesitas la integración de Java en el navegador (imagino que con algún plugin) o alguna configuración especial?

Estoy probando con la aplicación porque el plugin de [Autofirma](https://aur.archlinux.org/packages/autofirma/) no funciona bien desde hace tiempo en Firefox. En estos momentos no encuentro la forma de renovar mi certificado de Linux.¡Increíble, pero cierto! :-(

Gracias.

**Comment by ogarcia** [comment]
El entorno de escritorio me imagino que dará lo mismo. Yo lo he lanzado en XFCE y sin problema. Con instalar simplemente las dependencias (un java environment) y Chromium ya debería funcionar. No lo he probado con Firefox ni con otro navegador por lo que no te puedo decir si funciona (pero no me extrañaría que no lo hiciera). Ah, y es Arch Linux, nada de Manjaro ni otros derivados que terminan tocando los paquetes y teniendo dependencias distintas.

**Comment by ogarcia** [comment]
@Musikolo ¿Alguna novedad?

**Comment by Musikolo** [comment]
@ogarcia , pues no, todo sigue igual. Si hubiera alguna forma de reportar el problema a los desarrolladores de FNMT, pues quizá podría conseguir algún tipo de progreso a este respecto. En fin, como siempre, las aplicaciones de FNMT siempre con problemas... :-(

**Comment by ogarcia** [comment]
Lo extraño es que ni te abra la aplicación para generar la llave, porque ya te digo, en mi caso lo hace perfectamente en todas las máquinas en las que he probado

**Comment by Musikolo** [comment]
@ogarcia, he repetido todo el proceso desde una máquina virtual con Windows 7 en el que he instalado Autofirma y Configurador FNMT para Windows, pero aún así, me sigue saliendo el mismo error:

_[Error: No existe ningún certificado activo que se corresponda con la operación solicitada](https://www.sede.fnmt.gob.es/preguntas-frecuentes/errores-mas-comunes/errores-en-la-solicitud/-/asset_publisher/aEF1d5PdNxKA/content/error-no-existe-ningun-certificado-activo-que-se-corresponda-con-la-operacion-solicitada?inheritRedirect=false&redirect=https%3A%2F%2Fwww.sede.fnmt.gob.es%2Fpreguntas-frecuentes%2Ferrores-mas-comunes%2Ferrores-en-la-solicitud%3Fp_p_id%3D101_INSTANCE_aEF1d5PdNxKA%26p_p_lifecycle%3D0%26p_p_state%3Dnormal%26p_p_mode%3Dview%26p_p_col_id%3Dcolumn-2%26p_p_col_count%3D1)_

A pesar de lo que dice el mensaje, evidentemente, mi certificado está instalado en el navegador. Cuando inicio el proceso de renovación, me sale la ventana de validación del certificado, acepto, y entonces me sale el mensaje de  arriba. 

Por otro lado, también me funciona correctamente la página de _[Solicitar validación](https://www.sede.fnmt.gob.es/certificados/persona-fisica/verificar-estado/solicitar-verificacion)_ de mi certificado. El certificado fue expedido en una oficina de forma presencial, por lo que dudo que sea lo dice el segundo punto indicado en la página de aclaración del error.

Llegados a este punto creo que renovaré mi certificado en una oficina de forma presencial como hice la vez anterior. En fin, esto de FNMT como siempre, un dolor de cabeza.

Por último, visto lo visto, por favor, cierra el ticket si no se te ocurre nada para solucionarlo.

¡Muchas gracias! ;-)

**Comment by simonbcn** [comment]
A mi también me pasa lo mismo. En mi caso es que no tenía instalado `icedtea-web` para tener Java accesible desde el navegador (_en mi caso, Firefox_), debería ser una dependencia en el PKGBUILD, no?
