### ISSUE TITLE
configuradorfnmt - informe de uso

### ISSUE THREAD

**Issue by xmgz** [ogarcia/pkgbuilds#3]
Hola @ogarcia 

gracias por este "paquete". Sólo escribo para **informar de que funciona correctamente** (en apariencia), tras haberlo usado en el siguiente escenario:

- solicitar un **certificado de persona física en fnmt** utilizando el _dnie_ para identificarme.
- el **dnie** está correctamente instalado (desde siempre) tanto en chromium como en firefox
- he podido hacer la solicitud usando chromium, pero firefox **no** completaba el proceso.

entiendo que es un problema de la configuración de Firefox.

lo he instalado (arch, kernel-lte, kde) y utilizando el navegador **Chromium he podido realizar la solicitud sin problema.**

Con Firefox aparentemente también reconoce y llama a la aplicación _configuradorfnmt_, llega al punto de solicitar la clave PARA EL NUEVO CERTIFICADO (que hay que escribir usando este _configuradorfnmt_) y luego da un error inespecífico ("contacte con su admin", o algo así) que no he visto en su sección de ayuda.

Sólo escribo para agradecer tu trabajo e **informar por si alguien lee los issues** (tal como comentas en AUR).
Saludos

**Comment by ogarcia** [comment]
Perfecto. He puesto en el comentario de AUR fijado un enlace a esta _issue_. ¡Muchas gracias!

Y a cualquiera que lea esto, sentiros completamente libres de comentar aquí vuestra experiencia aunque la incidencia como tal este cerrada.

**Comment by c4tich** [comment]
¡Buenas! ¡De antemano quiero dar las gracias a @ogarcia por el currazo! Las administraciones públicas están dando un paso adelante para que podamos disponer de una identidad digital y así no tener que salir de casa para realizar gestiones, pero está claro que aún queda mucho trabajo, sobre todo para los que usamos Linux y más aún los que no tenemos una distro basada en Debian/RedHat. 

Quería comentar que en el pasado he usado `autofirma` con el paquete del AUR que subiste, @ogarcia y pude firmar digitalmente unos documentos que así lo requerían. Hoy, solicitando el certificado digital con DNIe, me encontré con `configuradorfnmt` y debo contar que no conseguí que me funcionara. El configurador me ayudó a llegar al paso de establecer una contraseña para el certificado y llegué a rellenar los datos que pide la página para el mismo, pero cuando le doy al botón de firmar, no se lanza autofirma (por eso comenté que antes lo he llegado a usar sin problemas). Pulsar el botón de firmar abre una ventana para abrir `xdg-open` que entiendo que lo hace es buscar qué aplicaciones pueden abrir una dirección con el protocolo ´fnmtcr://´ y al parecer no encuentra ninguna y falla. Los sucesivos intentos me dieron un fallo  al momento de intentar solicitar el certificado con DNIe, en el momento de pinchar en el botón. Creo que es el que dice que No tengo permisos para realizar la acción.

Como estaba con prisas por obtener el certificado para realizar un trámite (y por suerte o por desgracia) tengo acceso a una máquina "Windoze" con la que pude generar el certificado, pero si a alguien más le pasa esto, puedo intentar revocar mi certificado y seguir los pasos para reproducir el problema con el que me encontré, por ver si le evitamos a alguien que bootee en Windoze. También comento que usé Firefox ([de repos oficiales](https://archlinux.org/packages/extra/x86_64/firefox/)), Brave ([de AUR](https://brave.com/linux/#arch)) y [`ungoogled-chromium-bin`](https://aur.archlinux.org/packages/ungoogled-chromium-bin) antes de darme por vencido.

Saludos

**Comment by ogarcia** [comment]
Buenas @c4tich la verdad es que no se que decirte sobre todo el tema. Yo es que por ahora no tengo que renovar el certificado y ya sabemos que no es un software muy amigable que se preste a hacer pruebas.

Lo que comentas del protocolo `fnmtcr://`, ese protocolo lo maneja el _configuradorfnmt_, de hecho si revisas el [fichero desktop](https://aur.archlinux.org/cgit/aur.git/tree/configuradorfnmt.desktop?h=configuradorfnmt) verás que tiene un `MimeType=x-scheme-handler/fnmtcr;` para abrir ese tipo de direcciones. De hecho la web si requiere firma no debería abrirte _configuradorfnmt_, sino que debería de llamar al protocolo `afirma://` de _autofirma_ que esta también registrado en [su fichero desktop](https://aur.archlinux.org/cgit/aur.git/tree/autofirma.desktop?h=autofirma) en `MimeType=x-scheme-handler/afirma;`.

¿Has probado _autofirma_ pelado a ver si te funciona? Puedes probarlo aquí: https://sede.carm.es/cryptoApplet/ayuda/probarautofirma.html

Si ves que no te funciona una opción es abrir chromium (por poner un ejemplo) desde la línea de comandos de una consola para ir viendo los logs según va a haciendo las llamadas. A lo mejor eso te puede dar alguna pista.

Ya me contarás a ver si ves algo. ¡Saludos!

**Comment by Jarshvor** [comment]
Muchas gracias @ogarcia por el paquete.
Solo comentar que he podido solicitar el certificado de representante sin problemas en Firefox 108.0.2.
Me salió una ventana de Firefox preguntándome si quería permitir a 'Configurador FNMT' abrir el contenido tipo 'fnmtcr' o si deseaba usar otra aplicación.

Le dí a permitir, y listo.

**Comment by rodajc** [comment]
A mi también me funcionó sin problemas, aquí con firefox 120.0-1.

Al crear el paquete y después de configurar java-21-openjdk como entorno por defecto, me salió este mensaje:
```
resolving dependencies...
looking for conflicting packages...
:: jre-openjdk and jre-openjdk-headless are in conflict. Remove jre-openjdk-headless? [y/N] y

Packages (2) jre-openjdk-headless-21.u35-8 [removal]  jre-openjdk-21.u35-8

Total Download Size:    30,36 MiB
Total Installed Size:  152,92 MiB
Net Upgrade Size:        5,26 MiB

```
Supongo que será normal. El caso es que funcionó. Muchas gracias @ogarcia.

**Comment by Jarshvor** [comment]
> A mi también me funcionó sin problemas, aquí con firefox 120.0-1.
> 
> Al crear el paquete y después de configurar java-21-openjdk como entorno por defecto, me salió este mensaje:
> 
> ```
> resolving dependencies...
> looking for conflicting packages...
> :: jre-openjdk and jre-openjdk-headless are in conflict. Remove jre-openjdk-headless? [y/N] y
> 
> Packages (2) jre-openjdk-headless-21.u35-8 [removal]  jre-openjdk-21.u35-8
> 
> Total Download Size:    30,36 MiB
> Total Installed Size:  152,92 MiB
> Net Upgrade Size:        5,26 MiB
> ```
> 
> Supongo que será normal. El caso es que funcionó. Muchas gracias @ogarcia.
> 
> P.D. Al descargar el certificado, cuando ya no me lo esperaba, sale:
> 
> `Ha fallado la instalación por programa del certificado en Firefox en Linux`
> 
> Pero está instalado anyway.


Hola @rodajc, 
Hay una entrada en Arch News donde se explica el cambio de los paquetes JDK/JRE y el porqué del conflicto.
Puedes verla aquí:
[](https://archlinux.org/news/incoming-changes-in-jdk-jre-21-packages-may-require-manual-intervention/)

saludos
