### ISSUE TITLE
error running Autofirma

### ISSUE THREAD

**Issue by carlosnewmusic** [ogarcia/pkgbuilds#4]
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class java.awt.Toolkit at java.desktop/java.awt.Color.<clinit>(Color.java:275) at es.gob.afirma.standalone.LookAndFeelManager.<clinit>(LookAndFeelManager.java:60) at es.gob.afirma.standalone.SimpleAfirma.main(SimpleAfirma.java:549)

**Comment by ogarcia** [comment]
A ver, pocos datos me das.

Autofirma al arrancar da bastantes errores pero eso no implica que no funcione.  Si ejecutas el comando `autofirma` ¿Carga la interfaz?.

Puedes probar lanzando lo siguiente:
```bash
export _JAVA_OPTIONS='-Dswing.systemlaf=javax.swing.plaf.metal.MetalLookAndFeel'
autofirma
```
Así se descarta también que tengas algo tocando a las opciones de java.

Otra prueba que puedes hacer es mirar si tienes gtk3, no es necesario en Arch Linux base para autofirma, pero si tienes Arch Linux de algún sabor (como Manjaro) las dependencias pueden cambiar.

**Comment by ogarcia** [comment]
@carlosnewmusic ¿Has podido probar algo de lo que te he comentado? Si no cierro la Issue

**Comment by ogarcia** [comment]
@carlosnewmusic como no hay feedback entiendo que se ha solucionado el problema. Cierro el ticket, en cualquier caso puedes comentar sin problemas.

**Comment by carlosnewmusic** [comment]
> A ver, pocos datos me das.
> 
> Autofirma al arrancar da bastantes errores pero eso no implica que no funcione. Si ejecutas el comando `autofirma` ¿Carga la interfaz?.
> 
> Puedes probar lanzando lo siguiente:
> 
> ```shell
> export _JAVA_OPTIONS='-Dswing.systemlaf=javax.swing.plaf.metal.MetalLookAndFeel'
> autofirma
> ```
> 
> Así se descarta también que tengas algo tocando a las opciones de java.
> 
> Otra prueba que puedes hacer es mirar si tienes gtk3, no es necesario en Arch Linux base para autofirma, pero si tienes Arch Linux de algún sabor (como Manjaro) las dependencias pueden cambiar.

si al ejecutarlo desde terminal después de haber ejecutado el export abre la interfaz grafica

**Comment by ogarcia** [comment]
> si al ejecutarlo desde terminal después de haber ejecutado el export abre la interfaz grafica

Entonces mi consejo es que pongas esa línea directamente en `/usr/bin/autofirma` al final del todo justo después de `# Run app`, de tal forma que quede:
```
# Run app
export _JAVA_OPTIONS='-Dswing.systemlaf=javax.swing.plaf.metal.MetalLookAndFeel'
java -jar /usr/share/java/autofirma/autofirma.jar $@
```

De todas formas, yo revisaría el sistema porque tienes algo que te esta modificando las opciones de java y te esta forzando un valor de _LookAndFeel_ que, o bien no existe, o bien no tienes instalado.

**Comment by carlosnewmusic** [comment]
> > ¿Como lo reviso? el único paquete parecido a lo que me dices es este https://aur.archlinux.org/packages/kcm-lookandfeel-standalone-git que no lo tengo instalado
> 
> Eso no te puedo decir, cada sistema es un mundo y puede haber mil cosas distintas que modifiquen valores de JAVA. Lo único que te puedo decir es que en Arch Linux base con un escritorio completo de GNOME el valor del look and feel de Java no esta modificado. Tambien he probado a instalarla en un Manjaro LXDE pelado del todo y sin problemas.

es Manjaro XFCE, ¿como puedo ver las variables modificadas? vamos las que tiene mi sistema
