### ISSUE TITLE
Error cuando se está creando el certificado al llamar al configurador

### ISSUE THREAD

**Issue by Isaac-Martinez-Forte** [ogarcia/pkgbuilds#6]
Hola, buenos días,
estoy tratando de solicitar un certificado en la FNMT, he instalado el configurador desde AUR y parece que todo funciona bien pero al rato de hacer la llamada al configurador desde la web devuelve este problema:

Error generando el PKCS#8.
![image](https://user-images.githubusercontent.com/9163630/124259482-d7c62e00-db2e-11eb-8b96-508b2bcb6060.png)

Lo he probado con varios navegadores, chromium, firefox y chrome, y siempre pasa lo mismo.

No se si es relevante, pero utilizo Manjaro con KDE.

Un saludo, gracias.

**Comment by ogarcia** [comment]
Buenas,

Entiendo que este error te lo da cuando solicitas la llave, es decir, una vez que introduces el DNI, primer apellido y el correo electrónico en el punto 2. de la web (Solicitar certificado).

A ver, con Arch Linux limpio usando Firefox yo no he tenido ningún problema, pero Manjaro tiene la manía de modificar paquetes y posiblemente algo falte, puedes probar a instalar `jre8-openjdk` y [poner por defecto java8](https://wiki.archlinux.org/title/Java) como máquina virtual a ver si te funciona.

Otra opción es que lances firefox desde una consola poniendo antes este export:
```
export _JAVA_OPTIONS='-Dswing.systemlaf=javax.swing.plaf.metal.MetalLookAndFeel'
```

También te aconsejo que instales `gtk3` porque por defecto java usa GTK y tu al tener KDE posiblemente solo tengas QT.

Y la verdad es que poco mas te puedo decir. Este software es bastante malo y al no tener los fuentes no se puede recompilar ni revisar.

Saludos.

**Comment by mcat95** [comment]
Buenas tardes!

Justo me acabo de topar yo con este mismo error. En mi caso, la aplicación del configurador se abre, y llega a pedir una contraseña. Una vez la confimas, se cierra el configurador, se queda cargando la web durante ~10 segundos y salta el error que menciona @Isaac-Martinez-Forte 

Datos del sistema:
Versión de java: Openjdk-8
```
➜  ~ archlinux-java status
Available Java environments:
  java-11-openjdk
  java-8-openjdk (default)
➜  ~ java -version
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (build 1.8.0_292-b10)
OpenJDK 64-Bit Server VM (build 25.292-b10, mixed mode)
```

Corriendo gnome desde Linux 5.12.13, y reproducible desde Firefox, chromium y chrome

No se si es demasiado casualidad que justo me haya encontrado este issue a 1 hora de que se haya abierto, así que sospecho que quizás podría ser algún fallo puntual en los servidores del FNMT (?), aunque no tengo ni idea.

**Comment by ogarcia** [comment]
@mcat95 yo en mis pruebas he usado java por defecto y me ha completado el proceso
```
$ archlinux-java status
Available Java environments:
  java-16-openjdk (default)
$ java -version
openjdk version "16.0.1" 2021-04-20
OpenJDK Runtime Environment (build 16.0.1+9)
OpenJDK 64-Bit Server VM (build 16.0.1+9, mixed mode)
```
Ahora bien, no me extrañaría en absoluto que el problema pueda venir de los servidores de esta gente, no tengo nada claro el grado de implicación del servidor a la hora de generar la llave, pero seguramente alguna petición chunga mete.

**Comment by mcat95** [comment]
@ogarcia Acabo de instalar `jdk-openjdk` y tras ponerlo por defecto he sido capaz de generar la petición correctamente.

No tengo claro la verdad que podría estar pasando, o si es implicación o no de la versión de Java o de los servidores de la FNMT

**Comment by ogarcia** [comment]
> @ogarcia Acabo de instalar `jdk-openjdk` y tras ponerlo por defecto he sido capaz de generar la petición correctamente.

Cojonudo

> No tengo claro la verdad que podría estar pasando, o si es implicación o no de la versión de Java o de los servidores de la FNMT

Ya digo, yo lo hice con `jdk-openjdk` y perfecto, pero vamos, no descarto el que los servidores estén haciendo de las suyas

**Comment by Isaac-Martinez-Forte** [comment]
Buenas tardes,
gracias por las respuestas, me acaba de funcionar poniendo por defecto la openjdk 15, con la openjdk 8 me daba el error anteriormente mencionado, no se si habrán tocado algo para que con ajva 8 no funcione.

Así que nada, con la 15 funciona en chromium, con otras versiones y otros navegadores no lo he probado.

Un saludo y muchas gracias

**Comment by ogarcia** [comment]
Perfecto entonces, cerramos la _issue_
