### ISSUE TITLE
Binario de Autofirma 1.7.1 disponible

### ISSUE THREAD

**Issue by Marzal** [ogarcia/pkgbuilds#7]
No se desde hace cuanto, pero ya está publicado el binario de esta versión, no es la última pero imagino que mejor que la 1.6.5 con la que ya algunas webs muestran error debe ser.

Por si te sirve para actualizar el paquete.

Un saludo y gracias por el trabajo.

https://firmaelectronica.gob.es/Home/Descargas.html

**Comment by ogarcia** [comment]
Leches, no me había enterado. Mañana actualizo el -bin. ¡ Muchas gracias @Marzal !

**Comment by ogarcia** [comment]
Actualizado en f204509026cfabb663adc7a82cc5cd69b546be9d :wink:
