### ISSUE TITLE
Error al intentar firmar desde Firefox 97

### ISSUE THREAD

**Issue by simonbcn** [ogarcia/pkgbuilds#8]
Firefox 97
Todo funciona bien, me muestra mi certificado pero después de seleccionarlo y pulsar aceptar me sale este error:

![2022-02-16_15-22](https://user-images.githubusercontent.com/428231/154284597-01e12704-1340-4df1-bca0-7e9c3cd657cb.png)

¿Alguna pista?

**Comment by ogarcia** [comment]
@simonbcn ¿Con que paquete?

**Comment by ogarcia** [comment]
Es extraño, acabo de probar con Firefox 97 en https://www.sededgsfp.gob.es/es/Paginas/TestAutofirma.aspx y me funciona correctamente.

¿Te pasa también si intentas firmar un fichero directamente abriendo autofirma?

**Comment by ogarcia** [comment]
Yo no soy capaz de reproducir el error (no al menos en Arch Linux). ¿También te falla si intentas hacer el test [aquí](https://www.sededgsfp.gob.es/es/Paginas/TestAutofirma.aspx)?

**Comment by simonbcn** [comment]
Probablemente el problema sea de la propia sede electrónica de la AEPD y los certificados usados. Da igual, he desinstalado este programa y con el certificado digital me he dado de alta en _Cl@ve Permanente_ y mucho más sencillo y rápido.
